services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # תגדיר את זה ב-Render Dashboard
      - key: RENDER_EXTERNAL_URL
        sync: false  # תגדיר את זה ב-Render Dashboard (כמו: your-app-name.onrender.com)